import type { Product } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageData = (id: string) => {
  const imageData = PlaceHolderImages.find(img => img.id === id);
  return {
    imageUrl: imageData?.imageUrl || 'https://picsum.photos/seed/error/600/600',
    imageHint: imageData?.imageHint || 'placeholder image'
  };
};

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Wireless Headphones',
    description: 'High-fidelity sound and noise cancellation.',
    longDescription: 'Experience immersive sound with these state-of-the-art wireless headphones. Featuring active noise cancellation, a 20-hour battery life, and a comfortable over-ear design. Perfect for music lovers and frequent travelers.',
    price: 199.99,
    ...getImageData('prod_001'),
    category: 'Electronics',
    stock: 25,
  },
  {
    id: 'prod_002',
    name: 'Cotton T-Shirt',
    description: 'Soft, breathable, and sustainably sourced.',
    longDescription: 'A wardrobe essential, this t-shirt is made from 100% organic cotton for a soft and comfortable feel. Its classic cut and durable construction make it perfect for everyday wear. Available in various colors.',
    price: 24.99,
    ...getImageData('prod_002'),
    category: 'Apparel',
    stock: 150,
  },
  {
    id: 'prod_003',
    name: 'Ceramic Mug Set',
    description: 'Set of 4 handcrafted minimalist mugs.',
    longDescription: 'Start your day right with this beautiful set of four ceramic mugs. Each mug is handcrafted and features a unique, minimalist design. They are microwave and dishwasher safe, combining style with practicality.',
    price: 49.99,
    ...getImageData('prod_003'),
    category: 'Home Goods',
    stock: 50,
  },
  {
    id: 'prod_004',
    name: 'Classic Hardcover Novel',
    description: 'A timeless story of adventure and discovery.',
    longDescription: 'Rediscover a literary classic with this beautifully bound hardcover edition. This novel has captivated readers for generations with its compelling characters and timeless themes. A must-have for any bookshelf.',
    price: 18.50,
    ...getImageData('prod_004'),
    category: 'Books',
    stock: 80,
  },
  {
    id: 'prod_005',
    name: 'Professional Laptop',
    description: 'Powerful, sleek, and ready for any task.',
    longDescription: 'Boost your productivity with this high-performance laptop. Equipped with the latest processor, a stunning display, and a lightweight design, it\'s built for professionals on the go. Features all-day battery life.',
    price: 1299.00,
    ...getImageData('prod_005'),
    category: 'Electronics',
    stock: 15,
  },
  {
    id: 'prod_006',
    name: 'Denim Jeans',
    description: 'Classic straight-fit for timeless style.',
    longDescription: 'Crafted from premium denim, these jeans offer both comfort and durability. The classic straight-fit design is versatile and never goes out of style. Perfect for casual outings or dressing up for a night out.',
    price: 89.99,
    ...getImageData('prod_006'),
    category: 'Apparel',
    stock: 120,
  },
  {
    id: 'prod_007',
    name: 'Scented Candle',
    description: 'Lavender and chamomile for relaxation.',
    longDescription: 'Create a tranquil atmosphere with this scented candle. Made from natural soy wax and infused with lavender and chamomile essential oils, it helps to calm the mind and promote relaxation. Burns for up to 50 hours.',
    price: 22.00,
    ...getImageData('prod_007'),
    category: 'Home Goods',
    stock: 200,
  },
  {
    id: 'prod_008',
    name: 'Non-Fiction Essays',
    description: 'A thought-provoking collection on modern life.',
    longDescription: 'Explore a wide range of topics in this insightful collection of essays. Written by a leading contemporary thinker, this book challenges perspectives on technology, culture, and society. A stimulating read for the curious mind.',
    price: 16.95,
    ...getImageData('prod_008'),
    category: 'Books',
    stock: 65,
  },
  {
    id: 'prod_009',
    name: 'Gaming Mouse',
    description: 'High-precision sensor and customizable RGB.',
    longDescription: 'Gain a competitive edge with this high-precision gaming mouse. It features an ultra-accurate optical sensor, programmable buttons, and customizable RGB lighting to match your setup. Ergonomically designed for long gaming sessions.',
    price: 65.00,
    ...getImageData('prod_009'),
    category: 'Electronics',
    stock: 40,
  },
  {
    id: 'prod_010',
    name: 'Wool Scarf',
    description: 'Stay warm with this 100% merino wool scarf.',
    longDescription: 'Wrap yourself in luxury with this incredibly soft and warm scarf. Made from 100% pure merino wool, it provides excellent insulation against the cold while being lightweight and breathable. A stylish and practical winter accessory.',
    price: 55.00,
    ...getImageData('prod_010'),
    category: 'Apparel',
    stock: 90,
  },
  {
    id: 'prod_011',
    name: 'Modern Wall Clock',
    description: 'Silent, non-ticking, minimalist design.',
    longDescription: 'This modern wall clock is a functional piece of art. Its minimalist design and silent, non-ticking mechanism make it a perfect addition to any room, from the office to the living room. Easy to hang and powered by a single AA battery.',
    price: 45.00,
    ...getImageData('prod_011'),
    category: 'Home Goods',
    stock: 75,
  },
  {
    id: 'prod_012',
    name: 'Sci-Fi Saga',
    description: 'The complete best-selling space opera.',
    longDescription: 'Embark on an epic journey across the galaxy with this complete collection of a best-selling sci-fi saga. This box set includes all the books in the series, known for its intricate world-building and memorable characters.',
    price: 75.00,
    ...getImageData('prod_012'),
    category: 'Books',
    stock: 30,
  },
];
